### ISSUE TITLE
Page Numbers and Official Link on UIST 2015 Paper

### ISSUE THREAD

**Issue by jayfo** [fogies/web-jayfo#103]

**Comment by jayfo** [comment]
@stevezhanggeek

**Comment by jayfo** [comment]
Bump @stevezhanggeek 

Get @depstein to help if you're unsure what to do.

**Comment by stevezhanggeek** [comment]
Sorry I didn't see the last notification :(
I just followed Daniel's commit and did a pull request; seems it passes the test

**Comment by jayfo** [comment]
Fixed in #110.
