### ISSUE TITLE
CHI 2016 Abandonment Thumb

### ISSUE THREAD

**Issue by jayfo** [fogies/web-jayfo#124]
Now that we also have the UbiComp 2016 paper, it feels weird for the UbiComp 2015 and CHI 2016 papers to share the same thumb. Any ideas for a different CHI 2016 image?

**Comment by depstein** [comment]
In the talk, I motivated it with a picture of buying a Fitbit off
craigslist. Though not our original idea, that could work?

The picture would be too small to decipher anyways.

~Daniel Epstein

**Comment by jayfo** [comment]
Right, I don't think that would work.

What about a crop down to focus on lapsing?

**Comment by depstein** [comment]
Something like this?

![image](https://cloud.githubusercontent.com/assets/2422190/16365608/57b4fdfe-3bba-11e6-9d98-35463c3e4874.png)

**Comment by jayfo** [comment]
Going with a blue highlight of lapsing, as we discussed.
