### ISSUE TITLE
Development Guidelines

### ISSUE THREAD

**Issue by karkar** [fogies/web-jayfo#131]
Dev guidelines is a dead link.

**Comment by jayfo** [comment]
What link are you describing, on what page?

This is live:

https://homes.cs.washington.edu/~jfogarty/development/

**Comment by karkar** [comment]
Link on page is using http and the one you sent is https. http is giving me
404.

On Wed, Jul 13, 2016 at 11:22 AM, James Fogarty <notifications@github.com>
wrote:

> What link are you describing, on what page?
>
> This is live:
>
> https://homes.cs.washington.edu/~jfogarty/development/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fogies/web-jayfo/issues/131#issuecomment-232443102>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABuc5Lxr43ejtZkz03XNqQ1mXOq3santks5qVSzPgaJpZM4JK-qW>
> .
>



-- 

Ravi Karkar

**Comment by jayfo** [comment]
This works fine for me in Firefox (though I have HTTPS-Everywhere in Chrome):

http://homes.cs.washington.edu/~jfogarty/development/

**Comment by jayfo** [comment]
We're talking about the README

**Comment by jayfo** [comment]
Fixed by using README now instead of development/index.html
