### ISSUE TITLE
post IEEE Pervasive Paper

### ISSUE THREAD

**Issue by depstein** [fogies/web-jayfo#146]
Got the Google Scholar alert today. I'll do it, but this is a reminder for me to do it when I have a second.

https://faculty.ist.psu.edu/choe/download/PervasiveComputing-2017-Choe-SemiAutomated.pdf

**Comment by depstein** [comment]
@jayfo I'm changing this paper to reference 2017 instead of 2016, since the magazine won't be out until then. Okay?

**Comment by jayfo** [comment]
That sounds right.

I can't figure out if the current J9 is currently published or what.  Journals.

http://onlinelibrary.wiley.com/doi/10.1111/opn.12127/full

**Comment by depstein** [comment]
The DOI resolves, so I'll add that as well.
