### ISSUE TITLE
UbiComp Workshop Paper

### ISSUE THREAD

**Issue by jayfo** [fogies/web-jayfo#64]
@karkar

Can you send a pull request with the workshop paper, then I'll merge that and Daniel's UbiComp paper at the same time.  Ask @depstein for help if you're unsure how the site works.

**Comment by karkar** [comment]
Done.

On Tue, Jul 21, 2015 at 1:40 PM, James Fogarty <notifications@github.com>
wrote:

> @karkar <https://github.com/karkar>
>
> Can you send a pull request with the workshop paper, then I'll merge that
> and Daniel's UbiComp paper at the same time. Ask @depstein
> <https://github.com/depstein> for help if you're unsure how the site
> works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fogies/web-jayfo/issues/64>.
>



-- 

Ravi Karkar

**Comment by jayfo** [comment]
Closed in #65
