### ISSUE TITLE
Add CSCW Paper

### ISSUE THREAD

**Issue by jayfo** [fogies/web-jayfo#82]
From here:

<https://dl.dropboxusercontent.com/u/17121147/cscw2016-lifelog-collaboration.pdf>

To Daniel, because CSCW.

**Comment by depstein** [comment]
You've published there as many times as I have ;-)

**Comment by depstein** [comment]
Your job to pick out a thumbnail.

**Comment by jayfo** [comment]
Percentages.

**Comment by jayfo** [comment]
![cscw2016](https://cloud.githubusercontent.com/assets/2163573/10638823/b7cb7bea-77c1-11e5-93a9-9f2ca74b80da.png)
