### ISSUE TITLE
Missing fabfile.py

### ISSUE THREAD

**Issue by depstein** [fogies/web-jayfo#84]
For some reason, the fabfile disappeared from the repo. Makes local debugging hard for those of us who don't have a copy :-)

**Comment by jayfo** [comment]
invoke build

invoke serve

**Comment by depstein** [comment]
Thanks. Requires me to invoke through jekyll instead of fabric, since
fabric relies on the fabfile.

~Daniel Epstein

**Comment by jayfo** [comment]
Invoke is the new Fabric.

Update your pip, then run the command as below.

**Comment by depstein** [comment]
I just wanted things to stay the same :-(

That worked. Thanks.

~Daniel Epstein

**Comment by jayfo** [comment]
You and the rest of the 2.7 community. Lousy Republicans.
